# Generated by Django 3.2.13 on 2023-09-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donqlick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donqlick',
            name='disorder_type',
        ),
        migrations.AddField(
            model_name='donqlick',
            name='discoder_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='actor1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='actor2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='admin1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='admin2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='admin3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='assoc_actor_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='assoc_actor_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='civilian_targeting',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='event_date',
            field=models.DateField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='event_id_cnty',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='event_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='fatalities',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='geo_precision',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='inter1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='inter2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='interaction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='iso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='source_scale',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='sub_event_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='timestamp',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donqlick',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
